### ISSUE TITLE
Konvoi handbuch einpflegen

### ISSUE THREAD

**Issue by MichaelThom** [TacticalTrainingTeam/ttt_handbuch#10]
tacticalteam.de/content/konvoi-handbuch
Aktualität prüfen
Drinkalot fragen ob dieser namentlich im Handbuch erwähnt werden möchte

**Comment by MichaelThom** [comment]
Soweit in Ordnung
Grafiken müssen noch komplett eingepflegt bzw. erstellt werden

**Comment by TheConen** [comment]
Bitte bei #69 weiterführen.
