### ISSUE TITLE
Verbesserung der Lesbarkeit des Codes

### ISSUE THREAD

**Issue by MichaelThom** [TacticalTrainingTeam/ttt_handbuch#13]
Ich wurde hier ein Python System vorschlagen, Sprich Code Abschnitte durch Einrückungen klarer strukturieren

Beispiel
\section{Ein Beispiel}
-> Tab Text
\subsection
-> Tab \eineFunktion{}
-> Tab -> Tab Funktionsgegenstand

weiter Vorschläge ?

**Comment by TheConen** [comment]
Ich als Programmierer sage dazu nur: Indentation ftw!

//Edit: Das mit dem closen war n verklicker.

**Comment by Stura7** [comment]
Hört sich gut an, habe mal geschaut ob es eine automatische Funktion dafür gibt, leider habe ich noch nichts gefunden.
Dafür habe ich in TeXStudio eine Aufräumfunktion gefunden ("Tools" --> "Hilfsdateien aufräumen") macht das gleich wie die AAA Datei. In TeXMaker gibt es auch eine Option dafür.

**Comment by MichaelThom** [comment]
Miktex (das ich benutze) hat afaik diese Funktion nicht direkt. (indirekt kann man es auch bei jedem Durchlauf im Anschluss die Dateien aufräumen lassen aber das kann halt auch zu Fehlern führen falls die Dateien für einen zweiten Lauf benötigt werden)

**Comment by Stura7** [comment]
MikTeX ist doch nur Umgebung, nutzt kein Programm für die Bearbeitung der TeX-Dokumente oder nimmst du Notepad. Jedenfalls habe ich in die gitignore-Datei die schon ein paar dateien eingetragen die er nicht mit uploadet.
