### ISSUE TITLE
Struktur

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#16]
Hallo Leute,

hier mal eine ungefähre Vorstellung davon, wie ich mir nachher den Aufbau des TTT-Handbuches vorstelle - ich weiß nicht, inwiefern ich damit durch das grätsche, was ihr bis jetzt bereits gemacht habt. Diskussion ist erwünscht.
- [x] Einleitung
- [x] Truppengattungen
  - [x] OPL
  - [x] Zugführung
  - [x] Infanterie
  - [x] Spezialeinheiten
  - [x] Logistik/MedEvac
  - [x] CAS
  - [x] Mechanisierte Infanterie
  - [x] Kampfpanzer
  - [x] Artillerie
- [x] Grundlagen
  - [x] Formationen
  - [x] Sicherungen
  - [x] Manöver / Bewegen im Gelände
  - [x] Funken / Kommunikation
  - [x] Auf-/Absitzen
  - [x] Erste Hilfe
  - [x] Verhalten bei Feindkontakt
- [x] Fortgeschrittenes
  - [x] Führen
    - [x] als OPL
    - [x] als Zugführer
    - [x] als Truppführer
  - [x] Logistik/MedEvac anfordern (5-Liner)
  - [x] CAS anfordern (5-Liner/9-Liner)
  - [x] Artillerie anfordern (5-Liner)
  - [x] Close Quarters Combat (CQB)
  - [x] Hubschrauber und Infanterie
  - [x] Sani, Sani!
  - [x] Konvoi
- [x] Tutorials
  - [x] TFAR
  - [x] CAS
- [x] Sonstiges

Gerade die Abschnitte Truppengattungen und Grundlagen sollten sich dabei in den einzelnen Abschnitten sehr kurz halten und pro Unterabschnitt maximal 3 Seiten lang sein, wobei eine Seite davon eine Art "Merkblatt" sein sollte (z.B. eine grafische Übersicht aller Formationen). Bei den Truppengattungen dürfte das teilweise auch auf einer Seite zu lösen sein. Generell möchte ich viel mit Merkblättern arbeiten, die das wichtigste zusammenfassen, und nur in dem Bereich "Tutorials" sehr ausführlich werden - z.B. mit dem Funkhandbuch oder dem JTAC-Handbuch. Ist jemand von den hier Beteiligten in der Erstellung von Grafiken mit Photoshop & Co bewandert?

**Comment by MichaelThom** [comment]
Im Prinzip kann man vieles denke ich relativ leicht hin und her schieben. Vorläufig hatte ich den Autoren die Freiheit gelassen ihre Abschnitte so zu strukturieren wie sie das gerne wollten.
Mein Vorschlag wäre zunächst einmal weiter content zu produzieren und sozusagen auf einen "Version 1.0 zu kommen"
Dann erst diesen Inhalt optimieren.

Photoshop naja ich kenn mich ein bischen damit aus kommt auf die Komplexität der Photoshop Aufgabe an. :)

Wenn ich das so richtig sehe betreffen die Änderungen ja im wesentlichen das AGA-Handbuch dessen Übersichtlichkeit auch mir von anderer Seite schonmal angetragen wurde. Ich möchte auch nochmal auf die Möglichkeit der YT Videos verweisen ( Die auch jemand erstellen müsste ) und die sinnvoll eingesetzt sicherlich den einen oder anderen Inhalt erweitern könnte.

**Comment by TheConen** [comment]
Ich habe keine Erfahrung im Erstellen von größeren LaTeX-Dokumenten, aber meine Erfahrung aus der Softwareentwicklung sagt mir: erst strukturieren, dann implementieren. Es dürfte ein massivst größerer Aufwand werden, im Nachhinein alles rumzuschieben (in der Softwareentwicklung nennt man das Refactoring), als alles von vornherein an die richtige Stelle zu packen. 
Mein Vorschlag wäre also, dass wir uns im Vorhinein auf eine Struktur einigen, die - wie in diesem Fall auch gegeben - relativ modular sein sollte, so dass man einfach Sachen hinzufügen, weglassen oder verschieben kann.
Nachdem wir uns auf eine Struktur festgelegt haben, sollten wir auch die Ordnerstruktur des Projektes dieser Struktur anpassen - dazu werde ich dann noch ein eigenes Issue erstellen.

**Comment by TheConen** [comment]
Wie lauten die Meinungen der anderen dazu?

**Comment by Stura7** [comment]
Hört sich gut an. Obowhl in LaTeX leichter sein sollte, etwas nachträglich an der Struktur zu ändern, da es hier so gut wie keine Abhängigkeiten vorfindet.

**Comment by Stura7** [comment]
Des Weiteren hätte ich gern noch einen kurzen Teil über UAV. ;-) Also kurze Erläuterung was sie können und wie man sie einsetzten kann / sollte.

**Comment by Stura7** [comment]
Vielleicht sollten wir uns auch einfach mal zusammen setzten und das im TS klären ist vielleicht einfach als über diese Platform.

**Comment by TheConen** [comment]
Sorry, dass ich mich jetzt erst melde, hatte die letzten Tage mit Klausuren zu tun.

Im TS treffen und das mal kurz durchzusprechen ist glaub ich die beste Lösung, wie seht ihr das?

**Comment by Stura7** [comment]
Conen wie sieht es aus mit Befehlen und Kommandos?

**Comment by Stura7** [comment]
Wolf, die Struktur steht zwar, aber die einzelnen Punkte müssen inhaltlich noch erarbeitet werden

**Comment by MichaelThom** [comment]
Ja, das kann man sich dann als issue neu anlegen. da aber die Struktur an sich erfüllt war -> close :)
