### ISSUE TITLE
Möglichkeit YT Videos?

### ISSUE THREAD

**Issue by MichaelThom** [TacticalTrainingTeam/ttt_handbuch#2]
Zur Diskussion:
kleine YT-Videos einpflegen (wirklich klein maximal 1 Minute) als Ausbildungsvertsärker?

**Comment by Stura7** [comment]
ich close das mal, da Video sich schlecht in einen PDF bzw. gedruckten Werk machen. Dies wäre ein eigenständiges Projekt
