### ISSUE TITLE
Struktur - pass 2

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#37]
Ich habe nochmal ein bisschen an der Struktur geschraubt (Branch: struktur-pass2, e4e710f5fbc127eb98738cce908753cf5108aebc) - Vorbild war die Struktur von Softwareprojekten in der Softwareentwicklung. 

Wenn jemand die ganzen Pfade in den .tex-Dateien bei \input und \includegraphics anpassen könnte, wäre das klasse - inhaltlich hab ich sonst erstmal nichts verändert, nur Dateien hin- und hergeschoben. Feedback zu der Struktur ist erwünscht.

**Comment by MichaelThom** [comment]
Irgendwie ist da das Hauptdokument ttt-bibel.tex flöten gegangen
wo soll das hin? zum Ordner out?

**Comment by Stura7** [comment]
die ttt-bibel.tex ist die root.tex in src

**Comment by TheConen** [comment]
Wie siehts aus? Würd das mit der Struktur gerne abschließen, damit ich inhaltlich weitermachen kann.

**Comment by Stura7** [comment]
Also ich bin mir gerade nicht sicher ob das mit dem Output-Ordner SInn ergibt. Standardmäßig wird das PDF in gleichen Verzeichnis erzeugt. Eine Umlenkung in eine übergeordnete Verzeichnis ebene habe ich nach nur durch umständlichste Konstrukte oder absolute Pfade gesehn. Vielleicht sollten wir dies anpassen.

**Comment by TheConen** [comment]
Das erzeugte PDF kann man ja manuell in den out-Ordner verschieben - das ist auch nicht so wichtig und lässt sich auch nachher noch problemlos ändern. Wichtig ist aktuell das anpassen der \input und \includegraphics Befehle - das muss jemand übernehmen, der die aktuelle Struktur besser kennt als ich und dementsprechend weiß, was er wo ändern muss. Einfach sich das issue eben selbst zuweisen, damit ich weiß, wer das übernimmt.

**Comment by Stura7** [comment]
So habe mal wieder ein lauffähiges Dokument erzeugt. Schau mal bitte ob es so passt. 
P.S. src\tex\fortgeschrittenes\karteUndMarkierungen\kompassUndKarte.tex konnte ich nicht zuordnen.

**Comment by TheConen** [comment]
Struktur soweit fertig gestellt, wenns keine Einwände gibt, wird das morgen ins master gemerged und darauf dann weiterentwickelt.
@Stura7 : Danke fürs Pfade anpassen :)
