### ISSUE TITLE
Thema Bewaffnung erweitern

### ISSUE THREAD

**Issue by MichaelThom** [TacticalTrainingTeam/ttt_handbuch#5]

**Comment by TheConen** [comment]
Auf die einzelnen Waffen einzugehen hat keinen großen Sinn - viel zu spezifisch. Den Part "Bewaffnung", wie er aktuell im AGA-Handbuch vorhanden ist, mit einer Beschreibung jeder einzelnen Waffe, würde ich so gerne wegfallen lassen. Das einzig sinnvolle wäre eine allgemeine Beschreibung der Waffenmechaniken - was dann aber wieder so grundlegend wäre, dass es nicht ins TTT-Handbuch muss. Vorstellen könnte ich mir unter der Kategorie "Sonstiges" eine Sammlung von Tipps wie "Lege den Key zum Granaten werfen um, damit du nicht ausversehen eine wirst".
