### ISSUE TITLE
Inhalt: Grundlagen - Formationen

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#50]

**Comment by MichaelThom** [comment]
ebenfalls erledigt oder?

**Comment by ghost** [comment]
Kann sich wer die branch mal anschauen? irgendwie sind die Bilder ned da wo sie hingehören...
Bei den Sicherungen passts

**Comment by Stura7** [comment]
Done.
Die Grafiken waren einfach zu groß, dass sie noch auf die Seite gepasst hätten.
der Befehl htbp beim begin ist eine abkürzung für: 
h - here (einbinden an der gleichen Stelle)
t - top (am Seitenanfang)
b - bottom (am Seitenende)
p - page (eigene Seite für Bilder)

da in diesen Fall "here" nicht anwendbar war, wurde das Bild auf die nächste Seite verschoben (top).
Will man das Bild expizit an der stelle habe muss man [!h] benutzen. Damit wird der Textfluss ignoriert und das Bild an dieser Stelle eingebunden.

**Comment by ghost** [comment]
ah danke! dann änder ich das gschwind :)

**Comment by Stura7** [comment]
hab schon alles angepasst :)

**Comment by ghost** [comment]
gut gut. grad gesehen :+1:

**Comment by ghost** [comment]
könnte geclosed werden, wenn mans wirklich bei den Grundlagen belässt... vlt. schreib ich noch bisschen was dazu.
