### ISSUE TITLE
Inhalt: Grundlagen - Sicherungen

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#51]

**Comment by MichaelThom** [comment]
An und für sich erledigt oder?

**Comment by Stura7** [comment]
nope - neue BIlder kommen noch. Conen bereitet da noch etwas vor.

**Comment by ghost** [comment]
könnte geclosed werden, wenn mans wirklich bei den Grundlagen belässt... vlt. schreib ich noch bisschen was dazu.
