### ISSUE TITLE
Inhalt: Grundlagen - Manöver/Bewegen im Gelände

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#53]

**Comment by MichaelThom** [comment]
Themen:
Skylining wurde ja schon gesagt.
-> Annäherung an Hügelkante geduckt
-> dann liegend 
verhindert frühzeitig Feinderkennung

Feind bekämpfung bei plötzlichen Kontakt hinter Hügelkante
-> Annäherung wie bei Skylining dann Feind erkannt -> ggf. Rückzug hinter Hügelkante
-> Position nach links oder rechts verlagen -> Über Hügelkante wirken Position wieder verlagern
