### ISSUE TITLE
Inhalt: Grundlagen - Funken/Kommunikation

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#54]
Edit @Stura7
Beschreibt die Kommunikation innerhalb und zwischen Trupps von Trupps

**Comment by MichaelThom** [comment]
Erleditscht?

**Comment by Stura7** [comment]
Ebenfalls noch nicht - Befehle werden zum Teil auf die Wichtigsten reduziert.

**Comment by MichaelThom** [comment]
Das neue Funkhandbuch: https://mega.nz/#!DM82RI6A!JGb6UMSCWXMjJ5ky-Zy_ybtSbiYQ1P_o_ThWRVn9dVQ

**Comment by Stura7** [comment]
Kommandos wird von Nachti überarbeitet
