### ISSUE TITLE
Inhalt: Grundlagen - Erste Hilfe

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#56]
Edit by @Stura7
Erläuterung des Combat Medical Systems für den Truppsoldaten. Die forgeschrittene Behandlung von Verletzungen wird in Kapitel #68 behandelt

**Comment by MichaelThom** [comment]
Grundlagen (Vorschläge):
oberste Priorität Feindbekämpfung
Wann nehme ich welches Verbandmaterial
Sicherung vs 1. Hilfe
Wann sag ich dem TF bescheid das wir Medevac brauchen

**Comment by Stura7** [comment]
zu beachten ist, dass es aber auch mit ACE übereinstimmen muss, da ACE soon (TM) verwendet werden soll. Des Weiteren kannst du auch Highhead fragen, der hat am Wochenende mal kurz über das Handbuch geschaut.

**Comment by MichaelThom** [comment]
Ja hier würde ich eher allgemein bleiben wollen und dann im spezifischen auf die Mods/Tutorials verweisen.

**Comment by ghost** [comment]
Ich werd die Tage mein Tutorial überarbeiten zu ACE, parallel kann ich mich ja hier dran setzen.
