### ISSUE TITLE
Inhalt: Grundlagen - Verhalten bei Feindkontakt

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#57]
Edit @Stura7
Die Überschrift spezifiziert das Thema. Wird von Nachti übernommen

**Comment by MichaelThom** [comment]
Erstmal ein paar Vorschläge:
Deckung suchen -> hardcover
Feind melden -> Verweis ggf. auf die Kontaktmeldung
Spätestens jetzt Schwerpunktwaffe auf Feind ausrichten
Reaktion je nach Feuerstatus (Grün / Gelb / Rot)
