### ISSUE TITLE
Inhalt: Fortgeschrittenes - Hubschrauber und Infanterie

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#67]
Edit @Stura
In diesen Abschnitt werden die wichtigsten Infomationen bezüglich den Verhalten zwischen Infanterie und Hubschrauber erläutert. 
Weitereführende Infomationen werden in #70 erläutert

**Comment by Stura7** [comment]
Bilder müssen überarbeitet werden, Linien aktuell unsauber gezeichnet

**Comment by Stura7** [comment]
Done with #99
