### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by TheConen** [TacticalTrainingTeam/ttt_handbuch#74]
Wir benötigen eine Lizenz für das Handbuch. Ich schlage die hier vor:

https://creativecommons.org/licenses/by-nc-sa/4.0/

Frage: Dürften wir als Urheber es dann trotzdem noch kommerziell verbreiten?

**Comment by SCiite** [comment]
Soweit ich das verstehe, nein.

**Comment by Stura7** [comment]
Bei dieser Version ist die kommerzielle Verbreitung erlaubt. [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)

**Comment by TheConen** [comment]
Dann dürfen aber alle das auch kommerziell verbreiten - so, wie ich die Lizenzen verstehe, gelten die ja immer nur für andere. D.h., mit der BY NC SA dürfen andere das nicht kommerziell verbreiten, wir als Urheber aber schon. Bin da aber kein Experte, deswegen frag ich lieber nochmal nach :D.

**Comment by Stura7** [comment]
Habe jetzt nochmal 1 Stunde gesucht, irrgendwie habe die genaue Passage nicht mehr gefunden und ich wollte nicht das ganze englische FAQ lesen.

Also hier von der FH Köln: http://www.fbi.fh-koeln.de/institut/personen/linde/publikationen/CCL_I.pdf Seite 3: "Vorteilhaft ist ebenfalls, dass eine parallele kommerzielle Verwendung des Inhalts durch den Urheber möglich beleibt."

Des Weiteren hatte ich hier auch noch etwas dazu gelesen, jedoch finde ich das Dokument von der FH köln besser.
http://www.rechtzweinull.de/archives/80-Creative-Commons-Lizenzen-Urheberrecht-Einraeumung-von-Nutzungsrechten-Einfuehrung.html

**Comment by MichaelThom** [comment]
Warum müssen wir das kommerziell nutzen wollen?
Das man das unter irgendeine Lizenz stellt okay, verstehe ich noch.
Aber für eine kommerzielle Nutzung wüsste ich spontan keinen Anwendungsfall für uns

**Comment by TheConen** [comment]
Angenommen, das Ding ist irgendwann mal in einem "endgültig fertigen" Status, möchte ich gerne in der Lage sein, das auch zu drucken und mir ins Regal stellen zu können.

**Comment by Stura7** [comment]
Zwar wäre dafür keine kommerzielle Nutzung erforderlich (Außer du willst es an andere Personen verkaufen). Aber es ist ja so, dass man sich durch eine Lizenz keine Rechte entziehen lassen will.
